name: Feature Request
description: Suggest an idea for this project
labels: ["enhancement"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        > ⚠️ **Before submitting:** Please give your feature request a descriptive title above.

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: "e.g. I'm always frustrated when [...]"

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
